### ISSUE TITLE
remove print call

### ISSUE THREAD

**Issue by pommedeterresautee** [Saluev/elasticsearch-ltr-py#1]
There is a unneeded call to `print` in `create_model`.
I think it has been used for debugging but is no more useful.
Would it be possible to remove it and update pip version?

**Comment by Saluev** [comment]
Hi Michaël,

My bad, will fix now. Thanks for the feedback!

**Comment by Saluev** [comment]
New version is on pypi now: https://pypi.org/project/elasticsearch-ltr/1.0.1/
